[package]
name = "audiostream"
version = "0.1.0"
authors = [ "peter@taricorp.net" ]

[dependencies.ao]
ao = "*"

[dependencies.vorbisfile]
git = "https://github.com/tari/vorbisfile.rs"

[dependencies.lazy_static]
git = "https://github.com/Kimundi/lazy-static.rs"
