[package]
name = "audiostream"
version = "0.1.1"
authors = [ "peter@taricorp.net" ]

[dependencies]
ao = "*"
lazy_static = "*"

[dependencies.vorbisfile]
git = "https://github.com/tari/vorbisfile.rs"

[dev-dependencies]
docopt_macros = "*"
